name: testembed_flutter
description: Firebase OTP + Circular Video test app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.2

  # Video (web embed)
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.23.1

  # SIM verification
  permission_handler: ^11.3.0
  http: ^1.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
